### ISSUE TITLE
Adding Custom Music Files

### ISSUE THREAD

**Issue by superthrust** [DeadlyBossMods/DBM-SoundEventsPack#1]
**Is your feature request related to a problem? Please describe.**
Not a Problem, but I am unable to add music files even after converting to .ogg and adding them into the LoadList.lua file

**Describe the solution you'd like**
Being able to add more custom music options for in dungeons or during encounters.

**Describe alternatives you've considered**
adding and converting my own music files, while adding the lines to the LoadList.lua file.

**Additional context**
        })
	insert(DBM.Music, {
		text	= "DireDocks",
		value	= "Interface\\AddOns\\DBM-SoundEventsPack\\Music\\Music_DireDireDocks.ogg"
	})

the above code doesnt seem to work when adding it in

**Comment by LAMM14** [comment]
yeah had the same issue since a long time ago hope this will get solved

**Comment by MysticalOS** [comment]
adding media to .Music table ONLY applies to the EventSoundMusicCombined option, which is off by default. The proper way to inject media is to also assign it to proper categories DungeonMusic, BattleMusic, and Defeat, allowing that song selection to be selectable in appropriate types.

The reason type assignments matter is final fantasy victory fanfar makes sense as victory music, not boss engagement music. Sephiroths battle music doesn't make sense playing when for victory, etc. Music needs to be correctly typed.

the DBM.Music table is just for the global override that unlocks all music in all categories, usually for debugging purposes.

**Comment by LAMM14** [comment]
I mean as super wrote before it worked like that some time ago. Reading about what you write I managed to add custom sounds to dbm.victory since it only requires the sound file name and the route, now the thing is it doesnt work that way on the encounters, Im not really good at coding so im not sure how to do that, thanks for answering in advance
