### ISSUE TITLE
DBM.XYZ Deprecated

### ISSUE THREAD

**Issue by HallowSL** [DeadlyBossMods/DBM-SoundEventsPack#2]
No longer works, even after changing function names to the new ones.

**Comment by MysticalOS** [comment]
Not sure what you mean, event sound events pack work just fine for me

**Comment by HallowSL** [comment]
with no changes to my own loadlist, and having updated dbm, I've been getting this error.

"Message: Interface\AddOns\DBM-HallowSoundPack\LoadList.lua:406: '<eof>' expected near 'end'
Time: Tue Feb 22 15:25:14 2022
Count: 1
Stack: Interface\AddOns\DBM-HallowSoundPack\LoadList.lua:406: '<eof>' expected near 'end'
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1545: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:884: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:871>

Locals: (*temporary) = "DBM-HallowSoundPack"

Message: Interface\AddOns\DBM-HallowSoundPack\LoadList.lua:406: '<eof>' expected near 'end'
Time: Tue Feb 22 15:25:22 2022
Count: 3
"

**Comment by QartemisT** [comment]
That's DEFINATELY a Lua error within your addons code, not ours.

Unless you can link a source code, not much I can do to provide help.
